name: ai-chat-bot

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Provision & Deploy on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22

          script: |
            set -e

            # A) Install Docker if not already installed
            if ! command -v docker &> /dev/null
            then
              echo "Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            else
              echo "Docker is already installed"
            fi

            # B) Install Nginx if not installed
            if ! command -v nginx &> /dev/null
            then
              echo "Installing Nginx..."
              sudo apt install -y nginx
              sudo systemctl start nginx
              sudo systemctl enable nginx
            else
              echo "Nginx is already installed"
            fi

            # C) Configure Nginx to reverse proxy to React Docker container
            sudo rm -f /etc/nginx/sites-enabled/default

            sudo tee /etc/nginx/sites-available/react-app.conf > /dev/null << 'EOF'
            upstream react_app {
              server 127.0.0.1:5173;
            }

            server {
              listen 80 default_server;
              listen [::]:80 default_server;
              server_name _;

              location / {
                proxy_pass         http://react_app;
                proxy_http_version 1.1;
                proxy_set_header   Upgrade $http_upgrade;
                proxy_set_header   Connection "upgrade";
                proxy_set_header   Host $host;
                proxy_cache_bypass $http_upgrade;
              }
            }
            EOF

            sudo ln -sfn /etc/nginx/sites-available/react-app.conf /etc/nginx/sites-enabled/react-app.conf
            sudo nginx -t
            sudo systemctl restart nginx

            # D) Pull latest code and build Docker image
            rm -rf ~/react-app
            mkdir -p ~/react-app
            cd ~/react-app

            git clone https://github.com/Prathmesh895/SKTC-delpoy.git .
            git fetch origin main
            git reset --hard origin/main

            sudo docker build -t react-app:latest .

            # E) Stop and remove old container if it exists
            sudo docker stop react-app || true
            sudo docker rm react-app || true

            # F) Run new container
            sudo docker run -d \
              --name react-app \
              -p 5173:80 \
              react-app:latest

            # G) Clean up dangling Docker images
            sudo docker image prune -f
